name: Code style

on: [push, pull_request]

jobs:
  spotless-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci.gradle.properties ~/.gradle/gradle.properties

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Check Spotless
        run: ./gradlew spotlessCheck